/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedTrainingRouteImport } from './routes/_authenticated/training'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as ApiAiRouteImport } from './routes/api/ai'
import { Route as ApiEnginePackRouteImport } from './routes/api/engine-pack'
import { Route as ApiOcrRouteImport } from './routes/api/ocr'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiAdminTrainingRouteImport } from './routes/api/admin/training'
import { Route as AuthenticatedBooksBookIdIndexRouteImport } from './routes/_authenticated/books.$bookId.index'
import { Route as AuthenticatedBooksBookIdPlayRouteImport } from './routes/_authenticated/books.$bookId.play'
import { Route as AuthenticatedBooksBookIdSummaryRouteImport } from './routes/_authenticated/books.$bookId.summary'
import { Route as ApiPublicTrainSplatRouteImport } from './routes/api/public/train/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrainingRoute = AuthenticatedTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnginePackRoute = ApiEnginePackRouteImport.update({
  id: '/api/engine-pack',
  path: '/api/engine-pack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOcrRoute = ApiOcrRouteImport.update({
  id: '/api/ocr',
  path: '/api/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAdminTrainingRoute = ApiAdminTrainingRouteImport.update({
  id: '/api/admin/training',
  path: '/api/admin/training',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBooksBookIdIndexRoute =
  AuthenticatedBooksBookIdIndexRouteImport.update({
    id: '/books/$bookId/',
    path: '/books/$bookId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBooksBookIdPlayRoute =
  AuthenticatedBooksBookIdPlayRouteImport.update({
    id: '/books/$bookId/play',
    path: '/books/$bookId/play',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBooksBookIdSummaryRoute =
  AuthenticatedBooksBookIdSummaryRouteImport.update({
    id: '/books/$bookId/summary',
    path: '/books/$bookId/summary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicTrainSplatRoute = ApiPublicTrainSplatRouteImport.update({
  id: '/api/public/train/$',
  path: '/api/public/train/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/scan': typeof AuthenticatedScanRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/api/ai': typeof ApiAiRoute
  '/api/engine-pack': typeof ApiEnginePackRoute
  '/api/ocr': typeof ApiOcrRoute
  '/api/tts': typeof ApiTtsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/admin/training': typeof ApiAdminTrainingRoute
  '/books/$bookId/play': typeof AuthenticatedBooksBookIdPlayRoute
  '/books/$bookId/summary': typeof AuthenticatedBooksBookIdSummaryRoute
  '/api/public/train/$': typeof ApiPublicTrainSplatRoute
  '/books/$bookId/': typeof AuthenticatedBooksBookIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/scan': typeof AuthenticatedScanRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/api/ai': typeof ApiAiRoute
  '/api/engine-pack': typeof ApiEnginePackRoute
  '/api/ocr': typeof ApiOcrRoute
  '/api/tts': typeof ApiTtsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/admin/training': typeof ApiAdminTrainingRoute
  '/books/$bookId/play': typeof AuthenticatedBooksBookIdPlayRoute
  '/books/$bookId/summary': typeof AuthenticatedBooksBookIdSummaryRoute
  '/api/public/train/$': typeof ApiPublicTrainSplatRoute
  '/books/$bookId': typeof AuthenticatedBooksBookIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/training': typeof AuthenticatedTrainingRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/api/ai': typeof ApiAiRoute
  '/api/engine-pack': typeof ApiEnginePackRoute
  '/api/ocr': typeof ApiOcrRoute
  '/api/tts': typeof ApiTtsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/admin/training': typeof ApiAdminTrainingRoute
  '/_authenticated/books/$bookId/play': typeof AuthenticatedBooksBookIdPlayRoute
  '/_authenticated/books/$bookId/summary': typeof AuthenticatedBooksBookIdSummaryRoute
  '/api/public/train/$': typeof ApiPublicTrainSplatRoute
  '/_authenticated/books/$bookId/': typeof AuthenticatedBooksBookIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/scan'
    | '/studio'
    | '/training'
    | '/upload'
    | '/api/ai'
    | '/api/engine-pack'
    | '/api/ocr'
    | '/api/tts'
    | '/auth/callback'
    | '/api/admin/training'
    | '/books/$bookId/play'
    | '/books/$bookId/summary'
    | '/api/public/train/$'
    | '/books/$bookId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/scan'
    | '/studio'
    | '/training'
    | '/upload'
    | '/api/ai'
    | '/api/engine-pack'
    | '/api/ocr'
    | '/api/tts'
    | '/auth/callback'
    | '/api/admin/training'
    | '/books/$bookId/play'
    | '/books/$bookId/summary'
    | '/api/public/train/$'
    | '/books/$bookId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/scan'
    | '/_authenticated/studio'
    | '/_authenticated/training'
    | '/_authenticated/upload'
    | '/api/ai'
    | '/api/engine-pack'
    | '/api/ocr'
    | '/api/tts'
    | '/auth/callback'
    | '/api/admin/training'
    | '/_authenticated/books/$bookId/play'
    | '/_authenticated/books/$bookId/summary'
    | '/api/public/train/$'
    | '/_authenticated/books/$bookId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiAiRoute: typeof ApiAiRoute
  ApiEnginePackRoute: typeof ApiEnginePackRoute
  ApiOcrRoute: typeof ApiOcrRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiAdminTrainingRoute: typeof ApiAdminTrainingRoute
  ApiPublicTrainSplatRoute: typeof ApiPublicTrainSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training': {
      id: '/_authenticated/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AuthenticatedTrainingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/engine-pack': {
      id: '/api/engine-pack'
      path: '/api/engine-pack'
      fullPath: '/api/engine-pack'
      preLoaderRoute: typeof ApiEnginePackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ocr': {
      id: '/api/ocr'
      path: '/api/ocr'
      fullPath: '/api/ocr'
      preLoaderRoute: typeof ApiOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/admin/training': {
      id: '/api/admin/training'
      path: '/api/admin/training'
      fullPath: '/api/admin/training'
      preLoaderRoute: typeof ApiAdminTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/books/$bookId/': {
      id: '/_authenticated/books/$bookId/'
      path: '/books/$bookId'
      fullPath: '/books/$bookId/'
      preLoaderRoute: typeof AuthenticatedBooksBookIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/books/$bookId/play': {
      id: '/_authenticated/books/$bookId/play'
      path: '/books/$bookId/play'
      fullPath: '/books/$bookId/play'
      preLoaderRoute: typeof AuthenticatedBooksBookIdPlayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/books/$bookId/summary': {
      id: '/_authenticated/books/$bookId/summary'
      path: '/books/$bookId/summary'
      fullPath: '/books/$bookId/summary'
      preLoaderRoute: typeof AuthenticatedBooksBookIdSummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/train/$': {
      id: '/api/public/train/$'
      path: '/api/public/train/$'
      fullPath: '/api/public/train/$'
      preLoaderRoute: typeof ApiPublicTrainSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedTrainingRoute: typeof AuthenticatedTrainingRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedBooksBookIdPlayRoute: typeof AuthenticatedBooksBookIdPlayRoute
  AuthenticatedBooksBookIdSummaryRoute: typeof AuthenticatedBooksBookIdSummaryRoute
  AuthenticatedBooksBookIdIndexRoute: typeof AuthenticatedBooksBookIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedTrainingRoute: AuthenticatedTrainingRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedBooksBookIdPlayRoute: AuthenticatedBooksBookIdPlayRoute,
  AuthenticatedBooksBookIdSummaryRoute: AuthenticatedBooksBookIdSummaryRoute,
  AuthenticatedBooksBookIdIndexRoute: AuthenticatedBooksBookIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiAiRoute: ApiAiRoute,
  ApiEnginePackRoute: ApiEnginePackRoute,
  ApiOcrRoute: ApiOcrRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiAdminTrainingRoute: ApiAdminTrainingRoute,
  ApiPublicTrainSplatRoute: ApiPublicTrainSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
